config/routes.rb
Rails.application.routes.draw do
	require 'sidekiq/web'
	require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :sessions => "user_sessions" }

  resource :user_session
  resources :users
  devise_scope :user do
    get '/login' => "user_sessions#new",      :as => :login
    get '/logout' => "user_sessions#destroy", :as => :logout
  end
  resources :dining_tables do
    collection do 
      get "left_panel"
    end
    resources :orders do
	    member do
		    get "new"
	    end
    end
  end
  resources :orders do
    member do
	   get "finish"
	   get "print"
	   get "valid"
	   get "cart"
	   get "ticket"
	   get "cheque"
	   get "cash"
	   get "multiPay"
	   get "multiPayOk"
	   get "dining_tables"
	   get "login"
	   get "is_print"
	   get "change_table"
    end 
    resources :order_items do
      member do
        get "add_item"
	get "add_new_item"
	get "remove_item"
	get "add_new_item_sup"
      end
    end 
  end

  resources :items do
    member do
	    get "add_item"
	    get "remove_item"
    end
  end
  root to:  'dining_tables#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
end

app/controllers/dining_tables_controller.rb
class DiningTablesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :show_cash
  before_action :show_cart
  before_action :show_cheque
  before_action :show_ticket
  before_action :show_total
  before_action :show_total_people
  def index
	  @dining_tables = DiningTable.where("current_order_id is not null and (select is_valid from orders where id = current_order_id) is false")
  end

  def new
=begin
    @dining_tables = DiningTable.where("current_order_id is not null")

    @table = DiningTable.create({:name_of => "N° #{@dining_tables.count+1}", :current_order_id => nil})
    @montant =  0 
    respond_to do |format|
                  format.html { render :edit }
                  format.js { render :action => "edit", :layout => false }#:json => @table.to_json }
    end
=end
	  @dining_table = DiningTable.new 
	  render :layout => false
  end

  def create
     @dining_table = DiningTable.new(dining_table_params)
     if @dining_table.save
	     render :json => { :dining_table => @dining_table.to_json }, :status => 200
     else
	     render :json => { :errors => @dining_table.errors.full_messages }, :status => 422
     end
  end

  def edit
    @table = DiningTable.where(id: params[:id]).first
    @montant = @table.active_order.blank? ? 0 : @table.active_order.order_items.map(&:amount).sum
    unless params[:order_id].blank?
	@order = @table.active_order	  
	if @order.is_valid
		redirect_to dining_tables_url
	end
    end 
    respond_to do |format|
		  format.html { render :edit }
		  format.js { render :action => "edit", :layout => false }#:json => @table.to_json }
    end
  end

  def left_panel
    respond_to do |format|
                  format.js { render :action => "left_panel", :layout => false }#:json => @table.to_json }
    end
  end

private

  def show_cash
	  session[:show_cash] = Setting.where("label = 'show_cash'").first.active if session[:show_cash].blank?
  end

  def show_cart
	  session[:show_cart] = Setting.where("label = 'show_cart'").first.active if session[:show_cart].blank?
  end

  def show_ticket
	  session[:show_ticket] = Setting.where("label = 'show_ticket'").first.active if session[:show_ticket].blank?
  end
  
  def show_cheque
	  session[:show_cheque] = Setting.where("label = 'show_cheque'").first.active if session[:show_cheque].blank?
  end

  def show_total
	  session[:show_total] = Setting.where("label = 'show_total'").first.active if session[:show_total].blank?
  end

  def show_total_people
	  session[:show_total_people] = Setting.where("label = 'show_total_people'").first.active if session[:show_total_people].blank?
  end




  def dining_table_params
	  params.require(:dining_table).permit!
  end
end

app/helpers/dining_tables_helper.rb
module DiningTablesHelper
	def get_table_name(id)
		DiningTable.where(id: id).last.name_of
	end
end

app/views/dining_tables/edit.html.erb
<div class="page">
	<div class="navbar">

		<div class="navbar-inner">
                        
    			<div class="left"><a href="#" class="back_tables link"><i class="icon icon-back"></i></a></div>
			<div class="center sliding" id="diningtable"><%= "#{@table.name_of}" %> 点菜</div>
    			<div class="right">
      				<!-- Right link contains only icon - additional "icon-only" class--><a href="#" class="link icon-only open-panel"><i class="icon icon-bars-blue"></i></a>
				<span id="number_people" style="display:none;"><%= @table.active_order.blank? ? 0 : @table.active_order.quantity %></span>
				<span id="number_order" style="display:none;"><%= @table.current_order_id %></span>
    			</div>
  		</div>
	</div>
  <div class="toolbar tabbar tabbar-scrollable">
    <div class="toolbar-inner">
      <a href="#tab-0" class="tab-link tab-link-active">自助餐</a>
      <a href="#tab-1" class="tab-link">Apéritifs</a>
      <a href="#tab-2" class="tab-link">Boissons</a>
      <a href="#tab-3" class="tab-link">Vins En Pichet</a>
      <a href="#tab-4" class="tab-link">Vins Rouges</a>
      <a href="#tab-5" class="tab-link">Vins Rosés</a>
      <a href="#tab-6" class="tab-link">Vins Blancs</a>
      <a href="#tab-7" class="tab-link">Digestifs</a>
      <a href="#tab-8" class="tab-link">Champagne</a>
    </div>
  </div>
  <div class="tabs-swipeable-wrap" style="height:350px; width: 100%;">
	  <% cache "order_#{@table.try(:active_order).try(:id)}" do %>
    <div class="tabs">
      <div id="tab-0" class="page-content tab tab-active">
	<div class="block" style="margin: 10px 0;">
	      <div class="row">
		      <% Item.where(category_id: 0).each do |item| %>
			      <% unless item.amount.blank?%>
					<div class="col-50 tablet-25">
						<div class="card demo-card-header-pic">
							<a href=<%="/orders/#{@table.try(:active_order).try(:id)}/order_items/#{item.id}/add_new_item"%> data-remote="true" class="item-link item-content"><div style="height: 17vw; background-image:url(<%=image_path(item.url)%>); font-weight:bold;color:#2196f3;background-repeat:no-repeat;background-size: auto 100%;background-position: right top;" valign="bottom" class="card-header"><span class="bl" style="font-size:small;background:none;"><%=item.label %></span></div></a>
						</div>
					</div>
				<% else %>
					<div class="col-50 tablet-25">
                                                <div class="card demo-card-header-pic">
							<a href=<%="/orders/#{@table.try(:active_order).try(:id)}/order_items/#{item.id}/add_new_item_sup"%> class="item-link item-content"><div style="height: 17vw; background-image:url(<%=image_path(item.url)%>); font-weight:bold;color:#2196f3;background-repeat:no-repeat;background-size: auto 100%;background-position: right top;" valign="bottom" class="card-header"><span class="bl" style="font-size:small;background:none;"><%=item.label %></span></div></a>
                                                </div>
                                        </div>
				<% end %>
		      <% end %>
	      </div>
        </div>
      </div>
      <div id="tab-1" class="page-content tab">
	<div class="block" style="margin: 10px 0;">
	      <div class="row">
		      <% Item.where(category_id: 1).each do |item| %>
			<div class="col-50 tablet-25">
				<div class="card demo-card-header-pic">
					<a href=<%="/orders/#{@table.try(:active_order).try(:id)}/order_items/#{item.id}/add_new_item"%> data-remote="true" class="item-link item-content"><div style="height: 17vw; background-image:url(<%=image_path(item.url)%>);background-repeat:no-repeat;background-size: auto 100%;background-position: right top;font-weight:bold;color:#2196f3;" valign="bottom" class="card-header"><%=item.label %></div></a>
				</div>
			</div>
		      <% end %>
	      </div>
        </div>
      </div>
      <div id="tab-2" class="page-content tab">
        <div class="block" style="margin: 10px 0;">
		<div class="row">
                      <% Item.where(category_id: 2).each do |item| %>
                        <div class="col-50 tablet-25">
                                <div class="card demo-card-header-pic">
					<a href=<%="/orders/#{@table.try(:active_order).try(:id)}/order_items/#{item.id}/add_new_item"%> data-remote="true" class="item-link item-content"><div style="height: 17vw;background-image:url(<%=image_path(item.url)%>);background-repeat:no-repeat;background-size: auto 100%;background-position: right top; font-weight:bold;color:#2196f3;" valign="bottom" class="card-header"><%=item.label %></div></a>
                                </div>
                        </div>
                      <% end %>
              </div>
        </div>
      </div>
      <div id="tab-3" class="page-content tab">
        <div class="block" style="margin: 10px 0;">
		<div class="row">
                      <% Item.where(category_id: 3).each do |item| %>
                        <div class="col-50 tablet-25">
                                <div class="card demo-card-header-pic">
					<a href=<%="/orders/#{@table.try(:active_order).try(:id)}/order_items/#{item.id}/add_new_item"%> data-remote="true" class="item-link item-content"><div style="height: 17vw;background-image:url(<%=image_path(item.url)%>);background-repeat:no-repeat;background-size: auto 100%;background-position: right top; font-weight:bold;color:#2196f3;" valign="bottom" class="card-header"><%=item.label %></div></a>
                                </div>
                        </div>
                      <% end %>
              </div>
        </div>
      </div>
      <div id="tab-4" class="page-content tab">
        <div class="block" style="margin: 10px 0;">
		<div class="row">
                      <% Item.where(category_id: 4).each do |item| %>
                        <div class="col-50 tablet-25">
                                <div class="card demo-card-header-pic">
					<a href=<%="/orders/#{@table.try(:active_order).try(:id)}/order_items/#{item.id}/add_new_item"%> data-remote="true" class="item-link item-content"><div style="height: 17vw;background-image:url(<%=image_path(item.url)%>);background-repeat:no-repeat;background-size: auto 100%;background-position: right top; font-weight:bold;color:#2196f3;" valign="bottom" class="card-header"><%=item.label %></div></a>
                                </div>
                        </div>
                      <% end %>
              </div>
        </div>
      </div>
      <div id="tab-5" class="page-content tab">
        <div class="block" style="margin: 10px 0;">
		<div class="row">
                      <% Item.where(category_id: 5).each do |item| %>
                        <div class="col-50 tablet-25">
                                <div class="card demo-card-header-pic">
					<a href=<%="/orders/#{@table.try(:active_order).try(:id)}/order_items/#{item.id}/add_new_item"%> data-remote="true" class="item-link item-content"><div style="height: 17vw;background-image:url(<%=image_path(item.url)%>);background-repeat:no-repeat;background-size: auto 100%;background-position: right top; font-weight:bold;color:#2196f3;" valign="bottom" class="card-header"><%=item.label %></div></a>
                                </div>
                        </div>
                      <% end %>
              </div>
        </div>
      </div>
      <div id="tab-6" class="page-content tab">
        <div class="block" style="margin: 10px 0;">
		<div class="row">
                      <% Item.where(category_id: 6).each do |item| %>
                        <div class="col-50 tablet-25">
                                <div class="card demo-card-header-pic">
					<a href=<%="/orders/#{@table.try(:active_order).try(:id)}/order_items/#{item.id}/add_new_item"%> data-remote="true" class="item-link item-content"><div style="height: 17vw;background-image:url(<%=image_path(item.url)%>); background-repeat:no-repeat;background-size: auto 100%;background-position: right top;font-weight:bold;color:#2196f3;" valign="bottom" class="card-header"><%=item.label %></div></a>
                                </div>
                        </div>
                      <% end %>
              </div>
        </div>
      </div>
      <div id="tab-7" class="page-content tab">
        <div class="block" style="margin: 10px 0;">
		<div class="row">
                      <% Item.where(category_id: 7).each do |item| %>
                        <div class="col-50 tablet-25">
                                <div class="card demo-card-header-pic">
					<a href=<%="/orders/#{@table.try(:active_order).try(:id)}/order_items/#{item.id}/add_new_item"%> data-remote="true" class="item-link item-content"><div style="height: 17vw;background-image:url(<%=image_path(item.url)%>);background-repeat:no-repeat;background-size: auto 100%;background-position: right top; font-weight:bold;color:#2196f3;" valign="bottom" class="card-header"><%=item.label %></div></a>
                                </div>
                        </div>
                      <% end %>
              </div>
        </div>
      </div>
      <div id="tab-8" class="page-content tab">
        <div class="block" style="margin: 10px 0;">
		<div class="row">
                      <% Item.where(category_id: 8).each do |item| %>
                        <div class="col-50 tablet-25">
                                <div class="card demo-card-header-pic">
					<a href=<%="/orders/#{@table.try(:active_order).try(:id)}/order_items/#{item.id}/add_new_item"%> data-remote="true" class="item-link item-content"><div style="height: 17vw;background-image:url(<%=image_path(item.url)%>);background-repeat:no-repeat;background-size: auto 100%;background-position: right top; font-weight:bold;color:#2196f3;" valign="bottom" class="card-header"><%=item.label %></div></a>
                                </div>
                        </div>
                      <% end %>
              </div>
        </div>
      </div>
    </div>
<% end %>
  </div>
  <div class="md color-theme-blue" style="background:#2196f3; height:26px;line-height:2;padding:0 8px;">
	  <span style="float:left; color:#ffffff;">我的订单</span><span style="float:right;color:#FFFFFF; <%= Setting.where(label: "show_amount_screen").first.active ? '' : 'display:none;' %>">总额: <b id="amount_updated"><%= number_to_currency(@montant, :unit => "€") %></b></span> 
  </div>
  <div class="page-content" style="padding-top:0; overflow: auto;height: 200px;width:100%;">
	  <div class="block" style="margin:10px 0;">
	  <div class="row" id="items_choosen">
		  <% unless @table.active_order.blank? %>
			  <% @table.active_order.order_items.order("order_items.created_at desc, order_items.line_id desc").each do |oi| %>
			  	<% if oi.quantity < 0 %>
				<% else %>
					<div class="col-100 tablet-25" id="item_<%=oi.id%>">
						<div class="chip chip-c">
							<form data-remote="true"><button class="col button button-fill" formaction="<%="/orders/#{oi.order_id}/order_items/#{oi.id}/add_item"%>">+</button></form>
							<div class="chip-label chip-c-l"><%= oi.item.label %> <%=oi.try(:amount_v)%> <br> <span class="badge color-red"><%= oi.quantity %></span></div>
							<form data-remote="true"><button class="col button button-fill color-pink" formaction="<%="/orders/#{oi.order_id}/order_items/#{oi.id}/remove_item"%>">-</button></form>
						</div>
					</div>
				<% end %>
			  <% end %>
		  <% end %>
		  <% unless @table.active_order.blank? %>
                          <% @table.active_order.order_items.order("order_items.created_at desc, order_items.line_id desc").each do |oi| %>
                                <% if oi.quantity < 0 %>
                                        <div class="col-100 tablet-25" id="item_<%=oi.id%>">
                                                <div class="chip chip-co">
                                                        <div class="chip-label chip-co-l"><%= oi.item.label %> <%=oi.try(:amount_v)%> <br> <span class="badge color-red"><%= oi.quantity %></span></div>
                                                </div>
                                        </div>
                                <% end %>
                          <% end %>
                  <% end %>
	  </div>
	  </div>
  </div>


  <div class="toolbar tabbar-labels toolbar-bottom-md">
      <div class="toolbar-inner">
        <a href="<%=finish_order_path(@table.active_order.id)%>" class="link">
         	Annuler
        </a>
        <a href="<%=order_path(@table.active_order.id)%>" class="link">
		OK
        </a>
      </div>
    </div>
</div>

app/views/dining_tables/index.html.erb
<div class="page">
        <div class="navbar">
          <div class="navbar-inner">
            <div class="left">
              <a href="#" class="link icon-only panel-open" data-panel="left">
                      <i class="icon f7-icons ios-only">menu</i>
                <i class="icon material-icons md-only">menu</i>
              </a>
            </div>
	    <div class="title sliding">中国城中餐自助</div>
            <div class="right">
              <a class="link icon-only searchbar-enable" data-searchbar=".searchbar-components">
                <i class="icon f7-icons ios-only">search_strong</i>
                <i class="icon material-icons md-only">search</i>
              </a>
            </div>
            <form data-search-container=".components-list" data-search-in="a" class="searchbar searchbar-expandable searchbar-components searchbar-init">
              <div class="searchbar-inner">
                <div class="searchbar-input-wrap">
                  <input type="search" id="searchbar" placeholder="请输入桌号"/>
                  <i class="searchbar-icon"></i>
                  <span class="input-clear-button"></span>
                </div>
                <span class="searchbar-disable-button">Cancel</span>
              </div>
            </form>
          </div>
        </div>
	<div class="page-content" style="height:600px; overflow:auto;">
	  <div class="block-title searchbar-found">请点击加号添加餐桌 ：</div>
          <div class="list components-list searchbar-found">
				<ul class="actions-group actions-grid">
		    	<% @dining_tables.each do |dt| %>
						<li class="actions-button actions-button-text" style="height:auto; float:left;">
							<div class="actions-button-media" style="width:auto;">
								<% if dt.active_order.encour %>
									<a href="<%=order_path(dt.current_order_id)%>" class="item-content item-link" style="padding:0;"><img src="/assets/keman.png" width="87" style="background-color:<%=dt.user.color%>"></a>
								<% else %>
									<% if dt.user.id == current_user.id %>
										<a href="<%=edit_dining_table_path(dt)%>" class="item-content item-link" style="padding:0;"><img src="/assets/keman.png" width="87" style="background-color:<%=dt.user.color%>"></a>
									<% end %>
								<% end %>
							</div>
							<% if dt.active_order.encour %>
								<%= link_to raw("<div class='item-inner' style='padding:none;'><div class='item-title'>#{dt.name_of}</div></div>"), order_path(dt.current_order_id), {class: "item-content item-link", style: "background;none"}  %>
							<% else %>
								<% if dt.user.id == current_user.id %>
									<%= link_to raw("<div class='item-inner' style='padding:none;'><div class='item-title'>#{dt.name_of}</div></div>"), edit_dining_table_path(dt), {class: "item-content item-link", style: "background;none"}  %>
								<% end %>
							<% end %>
						</li>
			  <% end %>
				</ul>
           </div>
	</div>
    <div class="toolbar tabbar-labels toolbar-bottom-md">
      <div class="toolbar-inner">
	      <% if current_user.login == "admin" %>
        <a href="#" class="link" onclick="zhang.callCameraScan()">
          <i class="icon material-icons md-only size-22">crop_free</i>
	</a>
		<% end %>
        <a href="#" class="link" onclick="yu.loadWebview()">
          <i class="icon material-icons md-only size-22">autorenew</i>
        </a>
        <a href="<%=new_dining_table_path%>" class="link">
          <i class="icon material-icons md-only size-22">add</i>
        </a>
      </div>
    </div>
    </div>

app/views/dining_tables/left_panel.html.erb
<div class="page">
        <div class="page-content">
          <div class="block-title">我的信息</div>
          <div class="block">
                  <div class="block block-strong">
        <div class="chip">
          <div class="chip-media bg-color-red">
            <i class="icon f7-icons ios-only">person</i>
            <i class="icon material-icons md-only">person</i>
          </div>
          <div class="chip-label"><%= current_user.try(:login)%></div>
        </div>
                  </div>
                  <div class="chip color-red">
                          <div class="chip-label"><a href="#" class="item-link list-button" onclick="app.methods.signOut()">退出系统</a></div>
		  </div>



	  </div>

		<% if current_user.try(:login) == "admin" %>
		日期 ：<%= Date.today.to_s%>
<div class="block">
                        <div class="list no-hairlines-md" style="padding:0;margin:0;">
                              <ul>
                                <% if session[:show_cash] %>
                                <li class="item-content item-input">
                                  <div class="item-media">
                                        <i class="material-icons">
                                        euro_symbol
                                        </i>
                                        &nbsp;&nbsp; 现金 : <%= number_to_currency((Order.orders_today_cash_only + Order.orders_today_cash_multi), :unit => "€") %>
                                  </div>
                                </li>
                                <% end %>
                                <% if session[:show_cart] %>
                                <li class="item-content item-input">
                                  <div class="item-media">
                                    <i class="material-icons">
credit_card
                                    </i>
                                    &nbsp;&nbsp; 行卡 : <%= number_to_currency((Order.orders_today_cart_only + Order.orders_today_cart_multi), :unit => "€") %>
                                  </div>
                                </li>
                        <% end %>
                                <% if session[:show_cheque] %>
                                <li class="item-content item-input">
                                  <div class="item-media">
                                  <i class="material-icons">
picture_in_picture
                                  </i>
                                  &nbsp;&nbsp; 支票 : <%= number_to_currency((Order.orders_today_cheque_only + Order.orders_today_cheque_multi), :unit => "€") %>
                                  </div>
                                </li>
                        <% end %>
                                <% if session[:show_ticket] %>
                                <li class="item-content item-input">
                                  <div class="item-media">
                                          <i class="material-icons">
receipt
                                          </i>
                                          &nbsp;&nbsp; 饭票 : <%= number_to_currency((Order.orders_today_ticket_only + Order.orders_today_ticket_multi), :unit => "€") %>
                                  </div>
                                </li>
                        <% end %>
                                <% if session[:show_total] %>
                                <li class="item-content item-input">
                                  <div class="item-media">
                                          <i class="material-icons">
help_outline
                                          </i>
					  &nbsp;&nbsp; 金额 : <%= number_to_currency(Order.orders_today_encour.map{|l| l.try(:last_trace)}.map{|a| a.try(:amount)}.map(&:to_f).sum, :unit => "€") %>/<%= number_to_currency(Order.orders_today_all_amount, :unit => "€") %>
                                  </div>
                                </li>
                        <% end %>
                                <% if session[:show_total_people] %>
                                <li class="item-content item-input">
                                  <div class="item-media">
                                          <i class="material-icons">
help_outline
                                          </i>
                                          &nbsp;&nbsp; 人数 : <%= Order.orders_today_encour.map(&:quantity).sum %>/<%= Order.orders_today_all_people %>
                                  </div>
                                </li>
                        <% end %>
                              </ul>
                            </div>
                  </div>

		<% end %>

        </div> <!-- page-content -->
      </div> <!-- page -->

app/views/dining_tables/new.html.erb
<%= form_for @dining_table , :remote => true do |f|%>
<%= f.hidden_field :current_order_id, value: nil %>
  	<div class="list no-hairlines-md">
		<ul>
			<li class="item-content item-input">
				<div class="item-inner">
					<div class="item-title item-label">自定义桌号</div>
					<div class="item-input-wrap">
						<%= f.text_field :name_of,type:'text', placeholder: "自定义桌号", id: "chooseNameTable", class: "numpad", :onkeyup => "getLink()", :onblur => "getLink()", :onkeydown => "getLink()"%>
					</div>
				</div>
			</li>
			<li class="item-content item-input item-input-with-value">
<div class="item-inner">
<div class="item-title item-label">人数 </div>
<div class="item-input-wrap input-dropdown-wrap">
<select placeholder="Please choose..." class="input-with-value" id="chooseNbPeople" onchange="getLink()">
<option value="1">1</option>
<option value="2" selected>2</option>
<option value="3">3</option>
<option value="4">4</option>
<option value="5">5</option>
<option value="6">6</option>
<option value="7">7</option>
<option value="8">8</option>
<option value="9">9</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option>
<option value="13">13</option>
<option value="14">14</option>
<option value="15">15</option>
<option value="16">16</option>
<option value="17">17</option>
<option value="18">18</option>
<option value="19">19</option>
<option value="20">20</option>
<option value="21">21</option>
<option value="22">22</option>
<option value="23">23</option>
<option value="24">24</option>
<option value="25">25</option>
<option value="26">26</option>
<option value="27">27</option>
<option value="28">28</option>
<option value="29">29</option>
<option value="30">30</option>
<option value="31">31</option>
<option value="32">32</option>
<option value="33">33</option>
<option value="34">34</option>
<option value="35">35</option>
<option value="36">36</option>
<option value="37">37</option>
<option value="38">38</option>
</select>
</div>
</div>
			</li>
			<li class="item-content item-input" id="but_link"></li>
		</ul>
	</div>
	<% end %>