config/routes.rb
Rails.application.routes.draw do
	require 'sidekiq/web'
	require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :sessions => "user_sessions" }

  resource :user_session
  resources :users
  devise_scope :user do
    get '/login' => "user_sessions#new",      :as => :login
    get '/logout' => "user_sessions#destroy", :as => :logout
  end
  resources :dining_tables do
    collection do 
      get "left_panel"
    end
    resources :orders do
	    member do
		    get "new"
	    end
    end
  end
  resources :orders do
    member do
	   get "finish"
	   get "print"
	   get "valid"
	   get "cart"
	   get "ticket"
	   get "cheque"
	   get "cash"
	   get "multiPay"
	   get "multiPayOk"
	   get "dining_tables"
	   get "login"
	   get "is_print"
	   get "change_table"
    end 
    resources :order_items do
      member do
        get "add_item"
	get "add_new_item"
	get "remove_item"
	get "add_new_item_sup"
      end
    end 
  end

  resources :items do
    member do
	    get "add_item"
	    get "remove_item"
    end
  end
  root to:  'dining_tables#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :dining_table
	has_many :order_items, dependent: :destroy
	has_many :order_histories, dependent: :destroy

	def last_trace
		order_histories.order('created_at desc').first	
	end

	def self.orders_today
		self.where("date(created_at) = '#{Date.today.to_s}'").where("is_valid is true")
	end

	def self.orders_today_all_amount
		self.where("date(created_at) = '#{Date.today.to_s}' and (comments is null or comments != 'cancel')").map{|a| a.try(:last_trace)}.map{|a| a.try(:amount)}.map(&:to_f).sum
	end

	def self.orders_today_all_people
		self.where("date(created_at) = '#{Date.today.to_s}' and (comments is null or comments != 'cancel')").map(&:quantity).sum
	end

	def self.orders_today_encour
                self.where("date(created_at) = '#{Date.today.to_s}' and (comments is null or comments != 'cancel')").where("is_valid is false")
        end



	def self.orders_today_cash_only
		self.orders_today.where("payment_type = 'cash'").map(&:last_trace).map(&:amount).map(&:to_f).sum #.map(&:amount)
	end
	def self.orders_today_cart_only
		self.orders_today.where("payment_type = 'cart'").map(&:last_trace).map(&:amount).map(&:to_f).sum #.map(&:amount)
	end
	def self.orders_today_ticket_only
		self.orders_today.where("payment_type = 'ticket'").map(&:last_trace).map(&:amount).map(&:to_f).sum #.map(&:amount)
	end
	def self.orders_today_cheque_only
		self.orders_today.where("payment_type = 'cheque'").map(&:last_trace).map(&:amount).map(&:to_f).sum #.map(&:amount)
	end
	def self.orders_today_multiPay
		self.orders_today.where("payment_type = 'multiPay'").map(&:last_trace).map(&:amount).map(&:to_f).sum #.map(&:amount)
	end

	def self.orders_today_cash_multi
		self.orders_today.where("payment_type = 'multiPay'").map(&:comments).map{|m| eval(m)['cash'].gsub(',','.').to_f}.sum
	end

	def self.orders_today_cart_multi
                self.orders_today.where("payment_type = 'multiPay'").map(&:comments).map{|m| eval(m)['cart'].gsub(',','.').to_f}.sum
        end

	def self.orders_today_ticket_multi
                self.orders_today.where("payment_type = 'multiPay'").map(&:comments).map{|m| eval(m)['tkresto'].gsub(',','.').to_f}.sum
        end

	def self.orders_today_cheque_multi
                self.orders_today.where("payment_type = 'multiPay'").map(&:comments).map{|m| eval(m)['cheque'].gsub(',','.').to_f}.sum
        end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	skip_before_action :verify_authenticity_token


  def new
	  dining_table = DiningTable.new({name_of: "#{params[:dining_table_id]}",current_order_id: nil, user_id: current_user.id})
	  if dining_table.save 
		  order =  Order.new({dining_table_id: dining_table.id, quantity: params[:id]})
		  if order.save
			  #dining_table.update_attributes({current_order_id: order.id})
			  dining_table.update_attribute(:current_order_id, order.id);
			  render plain: "/dining_tables/#{dining_table.id}/edit", status: 200
		  else
			  render plain: "", status: 404
		  end
	  else
		  render plain: dining_table.errors.full_messages.first.to_s, status: 404 
	  end
  end

  def login
	  redirect_to login_path
  end

  def show
	  @order = Order.find(params[:id])
=begin
	  uniqId = define_uniqid SecureRandom.random_number(1000..9999)
	  #uniqId = Time.now.strftime("%m%d%H%M%S%L").to_s

	  amount = @order.order_items.map(&:amount).sum
	  detail = @order.order_items.map(&:detail).join(";")

	  last_order_history = @order.order_histories.order(:created_at).try(:last)
	  if last_order_history.blank? 
	  	OrderHistory.create({:order_id => @order.id, :amount => amount, :detail => detail, :uniqId => uniqId})
		@order.uniqId = uniqId
		@order.save
          else		  
		if last_order_history.amount != amount || last_order_history.detail != detail
			if !@order.is_valid
			OrderHistory.create({:order_id => @order.id, :amount => amount, :detail => detail, :uniqId => uniqId}) 
			@order.uniqId = uniqId
                	@order.save
			end
		end
	  end
	@order.encour = 1
	@order.save
=end
	#detail = "\nTable : #{@order.dining_table.name_of}, Service : #{current_user.login},    Date : #{Time.now.strftime('%d/%m/%Y %I:%M%p')}\n_______________________________\n#{@order.order_items.map{|oi| "#{oi.item.label} X #{oi.quantity}" }.join("\n")}|#{request.base_url}|#{@order.id}|#{@order.uniqId}"
        #render plain: detail, status: 200
  end

  def dining_tables
	  redirect_to dining_tables_url
  end

  def print
    @order = Order.find(params[:id])
    uniqId = define_uniqid SecureRandom.random_number(1000..9999) #Time.now.strftime("%m%d%H%M%S%L").to_s

    if @order.order_histories.length == 0
    	amount = @order.order_items.map(&:amount).sum
        detail = @order.order_items.map(&:detail).join(";")
        OrderHistory.create({:order_id => @order.id, :amount => amount, :detail => detail, :uniqId => uniqId, :printable => 1})
    else

	last_order_history = @order.order_histories.order(:created_at).try(:last)
	last_order_history.uniqId = uniqId
	last_order_history.printable = last_order_history.printable + 1
	last_order_history.amount = @order.order_items.map(&:amount).sum
	last_order_history.detail = @order.order_items.map(&:detail).join(";")
	last_order_history.save
    end

    @order.uniqId = uniqId
    @order.encour = 1
    @order.save

    total_amount = Setting.where(label: "show_amount_ticket").first.active ? "\nTotal : #{@order.order_histories.order(:created_at).try(:last).try(:amount)}" : ""

    detail = "\nTable : #{@order.dining_table.name_of}, Service : #{current_user.login},    Date : #{Time.now.strftime('%d/%m/%Y %I:%M%p')}\n_______________________________\n#{@order.order_items.order("line_id asc").map{|oi| (oi.quantity > 0 ? "#{oi.item.label} X #{oi.quantity}" : "#{oi.item.label} X #{oi.quantity}".split("").join("\u0336"))}.join("\n")}#{total_amount}|#{request.base_url}|#{@order.id}|#{@order.uniqId}"
        render plain: detail, status: 200
  end

  def change_table
	  dining_table = DiningTable.find(Order.find(params[:id]).dining_table_id)
	  if dining_table.update_attributes({name_of: params[:new_name]})
		@order = Order.find(params[:id])
          	uniqId = define_uniqid SecureRandom.random_number(1000..9999)		

		last_order_history = @order.order_histories.order(:created_at).try(:last)
		last_order_history.uniqId = uniqId
		last_order_history.printable = last_order_history.printable + 1
		last_order_history.save

		@order.uniqId = uniqId
		@order.save

		total_amount = Setting.where(label: "show_amount_ticket").first.active ? "\nTotal : #{last_order_history.try(:amount)}" : ""

		detail = "\nTable : #{dining_table.name_of}, Service : #{current_user.login},    Date : #{Time.now.strftime('%d/%m/%Y %I:%M%p')}\n_______________________________\n#{@order.order_items.order("line_id asc").map{|oi| (oi.quantity > 0 ? "#{oi.item.label} X #{oi.quantity}" : "#{oi.item.label} X #{oi.quantity}".split("").join("\u0336")) }.join("\n")}#{total_amount}|#{request.base_url}|#{@order.id}|#{@order.uniqId}|#{dining_table.name_of}"
		render plain: detail, status: 200
	  else
		render plain: dining_table.errors.full_messages.first.to_s, status: 404
	  end
  end

  def is_print
	order = Order.find(params[:id])
	last_order_history = order.order_histories.order(:created_at).try(:last)
	render plain: last_order_history.blank? ? false : order.order_histories.map(&:printable).sum > 0, status: 200
  end

  def finish
	  @order = Order.find(params[:id])
	  if @order.order_histories.size == 0 || @order.order_histories.order(:created_at).try(:last).printable == 0
		  @order.encour = 0
		  @order.comments = "cancel"
		  @order.save
		  @order.dining_table.update_attribute(:current_order_id,nil)
		  #dining_table = @order.dining_table
		  #dining_table.current_order_id = nil
		  #dining_table.save(validate:false)
		  @dining_tables = DiningTable.where("current_order_id is not null and (select is_valid from orders where id = current_order_id) is false")
	  else
		render plain: "non", status: 200
	  end
  end

  def valid
	  @order = Order.find(params[:id])
	  unless params[:promotion_id].blank?
		  if params[:promotion_id] == "0"
			  @order.order_items.each do |oi|
				  oi.update_attributes({:rate => nil})
			  end
		  else
			  p = Promotion.find(params[:promotion_id].to_i)
			  @order.order_items.each do |oi|
				if  p.items.map(&:id).include?(oi.item_id)
					oi.update_attributes({:rate => p.rate})
				end
			  end
		  end

		  last_order_history = @order.order_histories.order(:created_at).try(:last)
		  last_order_history.amount = @order.order_items.map(&:amount).sum.round(2)
		  last_order_history.detail = @order.order_items.map(&:detail).join(";")
		  last_order_history.save
	  end
  end

  def cash
    @order = Order.find(params[:id])
    @order.update_attributes({is_valid: true, payment_type: "cash", encour: false})
    @order.order_items.item_is_rank.each do |oi|
	    oi.item.update_attributes({:sold_number => oi.item.sold_number + oi.quantity})
    end
    detail = "\nTable : #{@order.dining_table.name_of}, Service : #{current_user.login},    Date : #{Time.now.strftime('%d/%m/%Y %I:%M%p')}\n_______________________________\n#{@order.order_items.map{|oi| "#{oi.item.label} X #{oi.quantity}" }.join("\n")}|#{request.base_url}/orders/#{@order.id}/valid"
    render plain: detail, status: 200
  end
  def cart
    @order = Order.find(params[:id])
    @order.update_attributes({is_valid: true, payment_type: "cart", encour: false})
    detail = "\nTable : #{@order.dining_table.name_of}, Service : #{current_user.login},    Date : #{Time.now.strftime('%d/%m/%Y %I:%M%p')}\n_______________________________\n#{@order.order_items.map{|oi| "#{oi.item.label} X #{oi.quantity}" }.join("\n")}\n CB : #{@order.order_items.map(&:amount).sum.round(2)}|#{request.base_url}/orders/#{@order.id}/valid"
    render plain: detail, status: 200
  end
  def ticket
    @order = Order.find(params[:id])
    @order.update_attributes({is_valid: true, payment_type: "ticket", encour: false})
    @order.order_items.item_is_rank.each do |oi|
	    oi.item.update_attributes({:sold_number => oi.item.sold_number + oi.quantity})
    end
    detail = "\nTable : #{@order.dining_table.name_of}, Service : #{current_user.login},    Date : #{Time.now.strftime('%d/%m/%Y %I:%M%p')}\n_______________________________\n#{@order.order_items.map{|oi| "#{oi.item.label} X #{oi.quantity}" }.join("\n")}|#{request.base_url}/orders/#{@order.id}/valid"
    render plain: detail, status: 200
  end
  def cheque
    @order = Order.find(params[:id])
    @order.update_attributes({is_valid: true, payment_type: "cheque", encour: false})
    @order.order_items.item_is_rank.each do |oi|
	    oi.item.update_attributes({:sold_number => oi.item.sold_number + oi.quantity})
    end
    detail = "\nTable : #{@order.dining_table.name_of}, Service : #{current_user.login},    Date : #{Time.now.strftime('%d/%m/%Y %I:%M%p')}\n_______________________________\n#{@order.order_items.map{|oi| "#{oi.item.label} X #{oi.quantity}" }.join("\n")}|#{request.base_url}/orders/#{@order.id}/valid"
    render plain: detail, status: 200
  end

  def create
		  order = Order.new(order_params)
		  if order.save
			  order.dining_table.update_attributes({current_order_id: order.id})
	          end
  end

  def multiPay
    @order = Order.find(params[:id])
    #@order.update_attributes({is_valid: true, payment_type: "multi"})
    #detail = "\nTable : #{@order.dining_table.name_of}, Service : #{current_user.login},    Date : #{Time.now.strftime('%d/%m/%Y %I:%M%p')}\n_______________________________\n#{@order.order_items.map{|oi| "#{oi.item.label} X #{oi.quantity}" }.join("\n")}|#{request.base_url}/orders/#{@order.id}/valid"
    #render plain: detail, status: 200
    render :layout => false
  end

 
  def multiPayOk
    @order = Order.find(params[:id])
    @order.update_attributes({is_valid: true, payment_type: "multiPay", comments: params.to_s, encour: false})
    @order.order_items.item_is_rank.each do |oi|
	    oi.item.update_attributes({:sold_number => oi.item.sold_number + oi.quantity})
    end
    detail = "\nTable : #{@order.dining_table.name_of}, Service : #{current_user.login},\nDate : #{Time.now.strftime('%d/%m/%Y %I:%M%p')}\n CB : #{params[:cart]}\n_______________________________\n#{@order.order_items.map{|oi| "#{oi.item.label} X #{oi.quantity}" }.join("\n")}|#{request.base_url}/orders/#{@order.id}/valid"

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/finish.html.erb
<div class="page">
        <div class="navbar">
          <div class="navbar-inner">
            <div class="left">
              <a href="#" class="link icon-only panel-open" data-panel="left">
                      <i class="icon f7-icons ios-only">menu</i>
                <i class="icon material-icons md-only">menu</i>
              </a>
            </div>
	    <div class="title sliding">中国城中餐自助</div>
            <div class="right">
              <a class="link icon-only searchbar-enable" data-searchbar=".searchbar-components">
                <i class="icon f7-icons ios-only">search_strong</i>
                <i class="icon material-icons md-only">search</i>
              </a>
            </div>
            <form data-search-container=".components-list" data-search-in="a" class="searchbar searchbar-expandable searchbar-components searchbar-init">
              <div class="searchbar-inner">
                <div class="searchbar-input-wrap">
		  <input type="search" id="searchbar" placeholder="请输入桌号"/>
                  <i class="searchbar-icon"></i>
                  <span class="input-clear-button"></span>
                </div>
                <span class="searchbar-disable-button">Cancel</span>
              </div>
            </form>
          </div>
        </div>
        <div class="page-content" style="height:600px; overflow:auto;">
	  <div class="block-title searchbar-found">请点击加号添加餐桌 ：</div>
          <div class="list components-list searchbar-found">
		  		<ul class="actions-group actions-grid">
                    <% @dining_tables.each do |dt| %>
                                                <li class="actions-button actions-button-text" style="height:auto;float:left;">
                                                        <div class="actions-button-media" style="width:auto;">
                                                                <% if dt.try(:active_order).try(:encour) %>
									<a href="<%=order_path(dt.current_order_id)%>" class="item-content item-link" style="padding:0;"><img src="/assets/keman.png" width="87" style="background-color:<%=dt.user.color%>"></a>
                                                                <% else %>
                                                                        <a href="<%=edit_dining_table_path(dt)%>" class="item-content item-link" style="padding:0;"><img src="/assets/keman.png" width="87" style="background-color:<%=dt.user.color%>"></a>
                                                                <% end %>
                                                        </div>
							<% if dt.active_order.encour %>
                                                                <%= link_to raw("<div class='item-inner' style='padding:none;'><div class='item-title'>#{dt.name_of}</div></div>"), order_path(dt.current_order_id), {class: "item-content item-link", style: "background;none"}  %>
                                                        <% else %>
                                                                <%= link_to raw("<div class='item-inner' style='padding:none;'><div class='item-title'>#{dt.name_of}</div></div>"), edit_dining_table_path(dt), {class: "item-content item-link", style: "background;none"}  %>
                                                        <% end %>
                                                </li>
                          <% end %>
                </ul>
           </div>
      </div>
	<div class="toolbar tabbar-labels toolbar-bottom-md">
      <div class="toolbar-inner">
              <% if current_user.login == "admin" %>
        <a href="#" class="link" onclick="zhang.callCameraScan()">
          <i class="icon material-icons md-only size-22">crop_free</i>
        </a>
                <% end %>
        <a href="#" class="link" onclick="yu.loadWebview()">
          <i class="icon material-icons md-only size-22">autorenew</i>
        </a>
        <a href="<%=new_dining_table_path%>" class="link">
          <i class="icon material-icons md-only size-22">add</i>
        </a>
      </div>
    </div>
</div>

app/views/orders/print.html.erb
<div class="page">
        <div class="navbar">

                <div class="navbar-inner">

                        <div class="left"><a href="#" class="back_tables link"><i class="icon icon-back"></i></a></div>
                        <div class="center sliding"><%= @order.dining_table.name_of %> 压桌单</div>
                        <div class="right">
                                <!-- Right link contains only icon - additional "icon-only" class--><a href="#" class="link icon-only open-panel"><i class="icon icon-bars-blue"></i></a>
                                <span id="number_people" style="display:none;"><%= @order.quantity %></span>
                        </div>
                </div>
	</div>
	<br><br><br>	
	<div class="data-table" style="height: 480px; overflow:auto;">
<table>
<thead>
<tr>
<th class="label-cell">Nom</th>
<th class="numeric-cell">Quantité</th>
<th class="numeric-cell">Montant</th>
</tr>
</thead>
<tbody>
	<% @order.order_items.each do |oi| %>
<tr>
	<td class="label-cell"><%= oi.item.label%></td>
	<td class="numeric-cell"><%=oi.quantity%></td>
	<td class="numeric-cell"><%=oi.item.amount * oi.quantity%></td>
</tr>
	<% end %>
</tbody>
</table>
	</div>

	<div class="block">
<p class="row">
<% if !@order.is_valid %>
<a href="<%=print_order_path(@order.id)%>" class="col button button-big button-fill color-green">打印</a>
<a href="<%=edit_dining_table_path(@order.dining_table_id)%>" class="col button button-big button-fill color-red">修改</a>
<% end %>
</p>
</div>
</div>

app/views/orders/show.html.erb
<div class="page">
        <div class="navbar">

                <div class="navbar-inner">

			<% if !@order.order_histories.blank? && @order.order_histories.order(:created_at).try(:last).printable > 0 %>
				<div class="left"><a href="/dining_tables" class="link"><i class="icon icon-back"></i></a></div>
				<div class="center sliding"><a href="<%=change_table_order_path(@order.id)%>"><span id="yazhuodan"><%= @order.dining_table.name_of %></span> 压桌单</a></div>
			<% else %>
				<div class="left"><a href="#" class="back_tables link"><i class="icon icon-back"></i></a></div>
				<div class="center sliding"><%= @order.dining_table.name_of %> 压桌单</div>
			<% end %>
                        <div class="right">
                                <!-- Right link contains only icon - additional "icon-only" class--><a href="#" class="link icon-only open-panel"><i class="icon icon-bars-blue"></i></a>
                                <span id="number_people" style="display:none;"><%= @order.quantity %></span>
                                <span id="number_order" style="display:none;"><%= @order.id %></span>
                        </div>
                </div>
	</div>
	<br><br><br>	
	<div class="data-table" style="height:480px;overflow:auto;">
<table>
<thead>
<tr>
<th class="label-cell">Nom</th>
<th class="numeric-cell">Quantité</th>
<th class="numeric-cell">Montant</th>
</tr>
</thead>
<tbody>
	<% @order.order_items.order("line_id").each do |oi| %>
 <tr>
	<td class="label-cell" bgcolor="<%=oi.quantity > 0 ? "" : "#ffcccc" %>"><%= oi.item.label%></td>
	<td class="numeric-cell" bgcolor="<%=oi.quantity > 0 ? "" : "#ffcccc" %>"><%=oi.quantity%></td>
	<td class="numeric-cell" bgcolor="<%=oi.quantity > 0 ? "" : "#ffcccc" %>"><%=oi.amount_v.blank? ? oi.item.amount : oi.amount_v%></td>
</tr>
	<% end %>
</tbody>
</table>
	</div>

	<% if !@order.is_valid %>
	<div class="toolbar tabbar-labels toolbar-bottom-md">
      <div class="toolbar-inner">
        <a href="<%=print_order_path(@order.id)%>" class="link">
          <i class="icon material-icons md-only size-22">print</i>
        </a>
        <a href="<%=edit_dining_table_path(@order.dining_table_id)%>" class="link">
		<i class="icon material-icons md-only size-22">edit</i>
        </a>
      </div>
	</div>
      <% end %>
</div>

app/views/orders/show.js.erb
//lee.funAndroid(<%=@detail%>,<%=@detail1%>, <%=@detail2%>, <%=@detail3"%>);

app/views/orders/valid.html.erb
<div class="page">
        <div class="navbar" style="line-height:3;">


			<center>确认单号 ：<%= @order.dining_table.name_of %></center>
        </div>
	<br><br><br>
	<% if @order.is_valid || @order.uniqId != params[:uniqId]  %>
		<div class="card">
			<div class="card-content card-content-padding"><center><b style="font-size: 20px; color: #cc0000;">此单已经支付或不是当日压桌单，故不能扫描</b><br><a href="#" class="button button-big button-raised" onclick="zhang.callCameraScan()">扫码</a></center><br><a href="#" class="button button-big button-raised" onclick="app.router.navigate('/dining_tables', {reloadCurrent:true, ignoreCache:true});">大厅</a>
			</div>
		</div>

	<% else %>
		<div class="data-table" style="height: 400px; overflow:auto;">
			<div class="card">
				<div class="card-content card-content-padding">
					<center><b style="font-size: 20px; color: #cc0000;"><%= number_to_currency(@order.order_items.map(&:amount).sum, :unit => "€")%></b></center>
				</div>
			</div>
  			<div class="card row">
						<% Promotion.all.each do |p| %>
							<% if @order.order_items.select{|oi| !oi.rate.blank?}.size > 0 %>
								<a href="/orders/<%=@order.id%>/valid?uniqId=<%=@order.uniqId%>&promotion_id=0" class="col button button-outline">取消 <%=p.short_label%></a>
							<%  else %>
								<a href="/orders/<%=@order.id%>/valid?uniqId=<%=@order.uniqId%>&promotion_id=<%=p.id%>" class="col button button-outline"><%=p.short_label%></a>
							<% end %>
                                                <% end %>
  			</div>
			<table>
			<thead>
			<tr>
			<th class="label-cell">Nom</th>
			<th class="numeric-cell">Quantité</th>
			<th class="numeric-cell">Montant</th>
			</tr>
			</thead>
			<tbody>
				<% @order.order_items.each do |oi| %>
			<tr>
				<td class="label-cell"><%= oi.item.label%></td>
				<td class="numeric-cell"><%=oi.quantity%></td>
				<% if oi.quantity > 0 %>
					<td class="numeric-cell"><%=oi.rate.blank? ? "" : "(#{oi.amount_v.blank? ? oi.item.amount : oi.amount_v} x #{oi.quantity}) x #{oi.rate}" %> <%= oi.amount  %></td>
				<% else %>
					<td class="numeric-cell"><%=oi.amount_v.blank? ? oi.item.amount : oi.amount_v %></td>
				<% end %>
			</tr>
				<% end %>
			</tbody>
			</table>
		</div>

		<div class="block">
			<p class="row">
			<a href="<%=cash_order_path(@order.id)%>" class="col button button-big button-fill color-green open-confirm"><button  label="Press Me" name="so_link" >现金</button></a>
			<a href="<%=cart_order_path(@order.id)%>" class="col button button-big button-fill color-red open-confirm"><button  label="Press Me" name="so_link" >刷卡</button></a>
			<a href="<%=ticket_order_path(@order.id)%>" class="col button button-big button-fill color-blue open-confirm"><button  label="Press Me" name="so_link" >饭票(c.v)</button></a>
			</p>
			<p class="row">
			<a href="<%=cheque_order_path(@order.id)%>" class="col button button-big button-fill color-blue open-confirm"><button  label="Press Me" name="so_link" >支票</button></a>
			<a href="<%=multiPay_order_path(@order.id)%>" class="col button button-big button-fill color-blue open-confirm"><button  label="Press Me" name="so_link" >多方式支付</button></a>
                        </p>
		</div>
	<% end %>
</div>